trigger:
  - master
   
pool:
  vmImage: 'ubuntu-latest'
   
stages:
  - stage: Build
    jobs:
      - job: Frontend
        steps:
        - task: NodeTool@0  
          inputs:  
            versionSpec: '10.x'  
          displayName: 'Install Node.js 10.x'  
        - task: Npm@1  
          displayName: 'Angular CLI'  
          inputs:  
            command: custom  
            verbose: false  
            customCommand: 'install @angular/cli'  
        - task: Npm@1  
          displayName: 'npm install'  
          inputs:  
            verbose: false  
        - task: Npm@1  
          displayName: Build  
          inputs:  
            command: custom  
            verbose: false  
            customCommand: 'run build'  
        - task: CopyPublishBuildArtifacts@1  
          displayName: 'Copy Publish Artifact: test'  
          inputs:  
            CopyRoot: dist  
            Contents: '**'  
            ArtifactName: test  
            ArtifactType: Container  
        - task: DownloadPipelineArtifact@2  
          displayName: 'Download Pipeline Artifact'  
          inputs:  
            targetPath: ' $(Build.ArtifactStagingDirectory)/dist/Presentation'
            
      - job: Backend
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
        # install dependencies
        - script: npm install
          displayName: npm install
        # build
        - script: npm run build
          displayName: npm run build
        - script: npm run units
          displayName: Run unit tests